### ISSUE TITLE
Send a status message on screen change

### ISSUE THREAD

**Issue by plains203** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#14]
It would be helpful in flows to have a message sent to stat when the screen is changed. It's something we can set with cmnd but there are use cases for tracking it.

**Comment by moinmoin-sh** [comment]
fixed with #15

**Comment by moinmoin-sh** [comment]
stat/ on unload
```
{
  "screen" : 3,
  "type" : "screen",
  "event" : "change",
  "state" : "unloaded"
}
```
stat/ on load
```
{
  "screen" : 4,
  "type" : "screen",
  "event" : "change",
  "state" : "loaded"
}
```

**Comment by sumnerboy12** [comment]
I wonder if it would be better to have a single screen `transition` event, with `from` and `to` screen IDs?

**Comment by moinmoin-sh** [comment]
possible ...
- my assumption was people are interested in the one or the other only
- transition requires one of the 9 known (fixed) screens, but may be there will be temporary screens or whatever in the future with an unknown screen number.
and from a code point of view is this way the clearest path because the unload and load event are seperate and if it should be a transition event the `from `would have to be stored until the to is available which I don't like
I like using the existing features instead of adding some bookkeeping code.

**Comment by sumnerboy12** [comment]
Fair enough - agree re. avoiding bookkeeping code where possible

**Comment by plains203** [comment]
Looks good
