### ISSUE TITLE
Can we add Text type item?

### ISSUE THREAD

**Issue by plains203** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#7]
I would like to be able to add Text type items for choosing inputs on my Home Theatre.

**Comment by moinmoin-sh** [comment]
Do you mean a tile with configurable text instead of an icon?

**Comment by plains203** [comment]
Yes that’s what I would like.

**Comment by moinmoin-sh** [comment]
Preview of the TEXT type tile.
Idea is to use it as a notification tile as well as a button, depending on the users configuration.
The text (instead of the icon) shall be set with a `setstate` cmnd/  and nothing via the configiuration. I think puttiing the text into the AdminUi would blow it up and reduce flexibility.
![grafik](https://user-images.githubusercontent.com/53935853/169409826-8fcbe9d7-9534-47b5-a160-25836960e63a.png)

**Comment by sumnerboy12** [comment]
I think this looks great - agree it is better suited to a command rather than config. Yet another thing that I think will be very useful!
